// -*- IDL -*-
//===========================================================================
/* Time-stamp: <2013-11-24 18:38:12 by jiangtao> */

/* @file Game_Platform.idl
 * $Id: Game_Platform.idl 2012/10/31 15:40:01 jiangtao Exp $
 *
 * @author:Jiangtao<jiangtao@tao-studio.net>
 */
//===========================================================================

#ifndef GAME_PLATFORM_IDL_
#define GAME_PLATFORM_IDL_
#include "Common.idl"
#include "Client_Node.idl"
#include "Server_Node.idl"
module GP
{
  interface User_Node;
  interface Platform_Node;

  interface Game_Platform
  {
    User_Node create_user(in Client_Node a_client_node);
    //todo:
    //application  
  };
};
#endif /* GAME_PLATFORM_IDL_ */
