// -*- IDL -*-
//===========================================================================
/* TIME-stamp: <2012-10-31 23:46:36 by jiangtao> */

/* @file Server_Node.idl
 * $Id: Server_Node.idl 2013/07/15 22:53:10 jiangtao Exp $
 *
 * @author:Jiangtao<jiangtao@tao-studio.net>
 */
//===========================================================================

#ifndef SERVER_NODE_IDL_
#define SERVER_NODE_IDL_

#include "Common.idl"

module GP
{
  interface Server_Node
  {
   
  };
};

#endif /* SERVER_NODE_IDL_ */
