// -*- IDL -*-
//===========================================================================
/* TIME-stamp: <2012-10-31 23:46:36 by jiangtao> */

/* @file User_Node.idl
 * $Id: User_Node.idl 2013/03/13 14:28:56 jiangtao Exp $
 *
 * @author:Jiangtao<jiangtao@tao-studio.net>
 */
//===========================================================================

#ifndef USER_NODE_IDL_
#define USER_NODE_IDL_
#include "Common.idl"
module GP
{
  // this object will be implemented @ server
  interface User_Node
  {
    void message(in Room_Id a_id,
                 in string a_message);


    void enter_room(in Room_Id new_room_id);
    void leave_room();
    void quit();     
  };
};

#endif /* USER_NODE_IDL_ */
